#ifndef SLIDEBUTTONLIB_GLOBAL_H
#define SLIDEBUTTONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SLIDEBUTTONLIB_LIBRARY)
#  define SLIDEBUTTONLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SLIDEBUTTONLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SLIDEBUTTONLIB_GLOBAL_H
